// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCE3dOs_6lUjXPL3m3L4TJs2b49P6XFL8',
    appId: '1:1050367978739:web:63ac4dc1ae5e93596a5b86',
    messagingSenderId: '1050367978739',
    projectId: 'metanoia-3b14b',
    authDomain: 'metanoia-3b14b.firebaseapp.com',
    storageBucket: 'metanoia-3b14b.appspot.com',
    measurementId: 'G-NPCSH43PEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_yGC-ffqJBMToNiarWNFBHTM10rdzBPM',
    appId: '1:1050367978739:android:f6f43828f90e79836a5b86',
    messagingSenderId: '1050367978739',
    projectId: 'metanoia-3b14b',
    storageBucket: 'metanoia-3b14b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYyKc4YVbCJhntOJ8zXyscm_MNsW9eh-8',
    appId: '1:1050367978739:ios:657960404cc555036a5b86',
    messagingSenderId: '1050367978739',
    projectId: 'metanoia-3b14b',
    storageBucket: 'metanoia-3b14b.appspot.com',
    iosClientId: '1050367978739-f73155dkcp7982nuecnij9q06206k0hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoMetanoia2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYyKc4YVbCJhntOJ8zXyscm_MNsW9eh-8',
    appId: '1:1050367978739:ios:657960404cc555036a5b86',
    messagingSenderId: '1050367978739',
    projectId: 'metanoia-3b14b',
    storageBucket: 'metanoia-3b14b.appspot.com',
    iosClientId: '1050367978739-f73155dkcp7982nuecnij9q06206k0hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoMetanoia2',
  );
}
